version: '3.8'

services:
  php-apache:
    container_name: tech-php-apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - '8888:80'
    volumes:
      - .:/var/www/html
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql
    networks:
      - techdev

  mysql:
    platform: linux/amd64
    image: mysql:8.0.26
    container_name: tech-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tech_management_db
      # MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - techdev

  adminer:
    image: adminer
    container_name: tech-adminer
    restart: always
    ports:
    - 8181:8080
    networks:
    - techdev

networks:
  techdev:
    driver: "bridge"

volumes:
  mysqldata:
    driver: local